package com.example.proyectoproductivo;

import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.Environment;
import android.support.v4.content.FileProvider;
import android.util.Log;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TemplatePDF {
    private Context context;
    Uri uri;
    private File pdfFile;
    private Document document;
    private PdfWriter pdfWriter;
    private Paragraph paragraph, paragraph2;
    private Font fTitle = new Font(Font.FontFamily.TIMES_ROMAN, 11, Font.BOLD);
    private Font fSubTitle = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.BOLD);
    private Font fText = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.BOLD);
    private Font fNormal = new Font(Font.FontFamily.TIMES_ROMAN, 7);
    private Font fCells = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.BOLD);

    public TemplatePDF(Context context) {
        this.context = context;
    }

    public void openDocument() {
        createFile();
    }

    private void createFile() {
    }

    /*public void closeDocument(){
        document.close();
    }*/
    public void addMetaData(Document document) {
        try {
            // get input stream
            InputStream ims = context.getAssets().open("header_pdf.png");
            Bitmap bmp = BitmapFactory.decodeStream(ims);
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            bmp.compress(Bitmap.CompressFormat.PNG, 100, stream);
            Image image = Image.getInstance(stream.toByteArray());

            float[] columnWidths = {1.5f, 5f};

            paragraph = new Paragraph();

            PdfPTable pdfPTable = new PdfPTable(columnWidths);
            pdfPTable.setWidthPercentage(108f);
            //cell.addElement(new Phrase(titulo,document.getContext().getDefaultFont()));
            paragraph2 = new Paragraph();
            float[] columnWidths2 = {3.8f, 2.2f};
            PdfPTable pdfPTable2 = new PdfPTable(columnWidths2);
            PdfPCell pdfPCell_1 = new PdfPCell(new Phrase(":", fSubTitle));
            pdfPCell_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_2 = new PdfPCell(new Phrase(" ", fSubTitle));
            pdfPCell_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_3 = new PdfPCell(new Phrase("\nFormato: PLAN DE INVERSIÓN PI COMPONENTE PROYECTO PRODUCTIVO - FEST\n ", fSubTitle));
            pdfPCell_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_4 = new PdfPCell(new Phrase("\nCódigo: F-GI-IP-91\n", fSubTitle));
            PdfPCell pdfPCell_5 = new PdfPCell(new Phrase(" ", fSubTitle));
            pdfPCell_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_6 = new PdfPCell(new Phrase(" ", fSubTitle));
            pdfPCell_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_7 = new PdfPCell(new Phrase("\nProceso: Gestión para la Inclusión Social\n ", fSubTitle));
            pdfPCell_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPCell_4.setVerticalAlignment(Element.ALIGN_LEFT);
            pdfPCell_7.setFixedHeight(30);
            PdfPTable pdfPTableFecha = new PdfPTable(1);
            PdfPCell pdfPCell_8 = new PdfPCell(new Phrase("Versión: 1 ", fSubTitle));
            PdfPCell pdfPCell_8_1 = new PdfPCell(new Phrase("Fecha Aprobación: FEBRERO/2019", fSubTitle));
            pdfPCell_8.setBorder(Rectangle.NO_BORDER);
            pdfPCell_8.setBorder(Rectangle.BOTTOM);
            pdfPCell_8_1.setBorder(Rectangle.NO_BORDER);
            pdfPTableFecha.addCell(pdfPCell_8);
            pdfPCell_8.setVerticalAlignment(Element.ALIGN_LEFT);
            pdfPTableFecha.addCell(pdfPCell_8_1);

            pdfPTable2.addCell(pdfPCell_3);
            pdfPCell_3.setFixedHeight(35);
            pdfPTable2.addCell(pdfPCell_4);
            pdfPCell_4.setFixedHeight(35);
            //  pdfPTable2.addCell(pdfPCell_5);
            //  pdfPTable2.addCell(pdfPCell_6);
            pdfPTable2.addCell(pdfPCell_7);
            pdfPCell_3.setFixedHeight(23);
            pdfPTable2.addCell(pdfPTableFecha);
            pdfPCell_3.setFixedHeight(13);
            image.scaleAbsolute(117, 31);
            PdfPTable TableImage = new PdfPTable(1);
            PdfPCell celda_externa_imagen = new PdfPCell();

            PdfPCell pdfPCell_Image = new PdfPCell();
            pdfPCell_Image.setFixedHeight(65);
            pdfPCell_Image.addElement(image);


            pdfPCell_Image.setVerticalAlignment(Element.ALIGN_MIDDLE);
            PdfPCell celda_derecha = new PdfPCell();
            celda_derecha.setUseBorderPadding(true);
            celda_derecha.setBorderWidthTop(1.7f);
            celda_derecha.setBorderWidthRight(1.7f);
            celda_derecha.setBorderWidthBottom(1.7f);

            pdfPTable2.setWidthPercentage(100);
            TableImage.addCell(pdfPCell_Image);
            TableImage.setWidthPercentage(100);
            celda_externa_imagen.addElement(TableImage);//la celda almacena tabla y a su vez almacena image
            celda_derecha.addElement(pdfPTable2);
            celda_externa_imagen.setBorderWidthTop(2f);
            celda_externa_imagen.setBorderWidthLeft(2f);
            celda_externa_imagen.setBorderWidthBottom(2f);
            celda_externa_imagen.setUseBorderPadding(true);
            pdfPTable.addCell(celda_externa_imagen);
            pdfPTable.addCell(celda_derecha);
            paragraph.add(pdfPTable);
            document.add(paragraph);

            SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
            Date date = new Date();

            float[] columnWidthsDate = {1f, 6f};
            paragraph = new Paragraph();
            PdfPTable pdfPTableDate = new PdfPTable(columnWidthsDate);
            pdfPTableDate.setWidthPercentage(108f);
            PdfPCell pdfPCell_Date1 = new PdfPCell(new Phrase("Fecha", fSubTitle));
            pdfPCell_Date1.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell pdfPCell_Date2 = new PdfPCell(new Phrase(String.valueOf(formatter.format(date)), fSubTitle));
            pdfPCell_Date2.setHorizontalAlignment(Element.ALIGN_LEFT);
            pdfPTableDate.addCell(pdfPCell_Date1);
            pdfPTableDate.addCell(pdfPCell_Date2);
            paragraph.add(pdfPTableDate);
            document.add(paragraph);
            paragraph = new Paragraph();


        } catch (IOException ex) {
            return;
        } catch (BadElementException e) {
            e.printStackTrace();
        } catch (DocumentException e) {
            e.printStackTrace();
        }


    }

    public void addTitles(Document document, String dato) {
        String[] tokens = dato.split(";");
        try {
            paragraph = new Paragraph();
            PdfPTable pdfPTableTitulo = new PdfPTable(1);
            pdfPTableTitulo.setWidthPercentage(108f);
            PdfPCell pdfPCell_Titulo = new PdfPCell(new Phrase("1. INFORMACIÓN GENERAL DEL HOGAR", fSubTitle));
            pdfPCell_Titulo.setFixedHeight(17);
            pdfPCell_Titulo.setBackgroundColor(new BaseColor(213, 235, 255));//176, 224, 230));
            pdfPCell_Titulo.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPCell_Titulo.setVerticalAlignment(Element.ALIGN_MIDDLE);
            pdfPTableTitulo.addCell(pdfPCell_Titulo);
            paragraph.add(pdfPTableTitulo);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsCUADRO = {2f, 2.9f, 0.7f, 2f, 2.7f, 1.31f, 2.69f, 2.6f, 0.23F};
            PdfPTable PTableC_INTERMEDIA = new PdfPTable(columnWidthsCUADRO);
            PTableC_INTERMEDIA.setWidthPercentage(108f);
            PdfPCell CELDA_INTERMEDIA1 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA3 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA6 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA7 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA8 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA9 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA10 = new PdfPCell(new Phrase("Departamento:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA11 = new PdfPCell(new Phrase(tokens[6], fSubTitle));
            PdfPCell CELDA_INTERMEDIA12 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA13 = new PdfPCell(new Phrase("Municipio:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA14 = new PdfPCell(new Phrase(tokens[7], fSubTitle));
            PdfPCell CELDA_INTERMEDIA15 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA16 = new PdfPCell(new Phrase("Corregimineto y vereda:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA17 = new PdfPCell(new Phrase(tokens[8], fSubTitle));
            PdfPCell CELDA_INTERMEDIA18 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA1.setFixedHeight(3);
            CELDA_INTERMEDIA2.setFixedHeight(3);
            CELDA_INTERMEDIA3.setFixedHeight(3);
            CELDA_INTERMEDIA4.setFixedHeight(3);
            CELDA_INTERMEDIA5.setFixedHeight(3);
            CELDA_INTERMEDIA6.setFixedHeight(3);
            CELDA_INTERMEDIA3.setFixedHeight(3);
            CELDA_INTERMEDIA8.setFixedHeight(3);
            CELDA_INTERMEDIA9.setFixedHeight(3);
            CELDA_INTERMEDIA1.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA1.setBorder(Rectangle.LEFT);
            CELDA_INTERMEDIA2.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA7.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA8.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA9.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA9.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA12.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA15.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA18.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA18.setBorder(Rectangle.RIGHT);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA1);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA2);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA3);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA4);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA5);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA6);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA7);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA8);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA9);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA10);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA11);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA12);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA13);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA14);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA15);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA16);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA17);
            PTableC_INTERMEDIA.addCell(CELDA_INTERMEDIA18);
            paragraph.add(PTableC_INTERMEDIA);
            document.add(paragraph);

            paragraph = new Paragraph();
            float[] columnWidthsCUADRO2 = {2.9f, 4.3f, 0.7f, 2.2f, 2.2f, 0.8f, 3.05f, 2.91f, 0.29F};
            PdfPTable PTableC_INTERMEDIA2 = new PdfPTable(columnWidthsCUADRO2);
            PTableC_INTERMEDIA2.setWidthPercentage(108f);
            PdfPCell CELDA_INTERMEDIA2_1 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_2 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_3 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_4 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_5 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_6 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_7 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_8 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_9 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_10 = new PdfPCell(new Phrase("Nombre completo del\n Titular del Hogar:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_11 = new PdfPCell(new Phrase(tokens[2] + " " + tokens[3] + " " + tokens[4], fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_12 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_13 = new PdfPCell(new Phrase("Documento de\n Identificación:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_14 = new PdfPCell(new Phrase(tokens[1], fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_15 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_16 = new PdfPCell(new Phrase("Teléfono y/o celular:", fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_17 = new PdfPCell(new Phrase(tokens[9], fSubTitle));
            PdfPCell CELDA_INTERMEDIA2_18 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA2_1.setFixedHeight(3);
            CELDA_INTERMEDIA2_2.setFixedHeight(3);
            CELDA_INTERMEDIA2_3.setFixedHeight(3);
            CELDA_INTERMEDIA2_4.setFixedHeight(3);
            CELDA_INTERMEDIA2_5.setFixedHeight(3);
            CELDA_INTERMEDIA2_6.setFixedHeight(3);
            CELDA_INTERMEDIA2_7.setFixedHeight(3);
            CELDA_INTERMEDIA2_8.setFixedHeight(3);
            CELDA_INTERMEDIA2_9.setFixedHeight(3);
            CELDA_INTERMEDIA2_1.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_1.setBorder(Rectangle.LEFT);
            CELDA_INTERMEDIA2_2.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_4.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_5.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_7.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_8.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_9.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_9.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA2_12.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_15.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_18.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA2_18.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA2_11.setVerticalAlignment(Element.ALIGN_MIDDLE);
            CELDA_INTERMEDIA2_14.setVerticalAlignment(Element.ALIGN_MIDDLE);
            CELDA_INTERMEDIA2_16.setVerticalAlignment(Element.ALIGN_MIDDLE);
            CELDA_INTERMEDIA2_17.setVerticalAlignment(Element.ALIGN_MIDDLE);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_1);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_2);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_3);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_4);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_5);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_6);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_7);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_8);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_9);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_10);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_11);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_12);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_13);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_14);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_15);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_16);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_17);
            PTableC_INTERMEDIA2.addCell(CELDA_INTERMEDIA2_18);
            paragraph.add(PTableC_INTERMEDIA2);
            document.add(paragraph);
            float[] columnWidthsCUADRO3 = {1.8f, 7f, 0.12f};
            paragraph = new Paragraph();
            PdfPTable pdfPTable3 = new PdfPTable(columnWidthsCUADRO3);
            pdfPTable3.setWidthPercentage(108f);
            PdfPCell CELDA_INTERMEDIA3_1 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA3_2 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA3_3 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA3_1.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA3_1.setBorder(Rectangle.LEFT);
            CELDA_INTERMEDIA3_2.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA3_3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA3_3.setBorder(Rectangle.RIGHT);
            PdfPCell CELDA_INTERMEDIA3_4 = new PdfPCell(new Phrase("Cambio de titularidad", fSubTitle));
            PdfPCell CELDA_INTERMEDIA3_5 = new PdfPCell(new Phrase(tokens[10], fSubTitle));
            PdfPCell CELDA_INTERMEDIA3_6 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA3_1.setFixedHeight(3);
            CELDA_INTERMEDIA3_2.setFixedHeight(3);
            CELDA_INTERMEDIA3_6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA3_6.setBorder(Rectangle.RIGHT);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_1);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_2);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_3);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_4);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_5);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_6);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_1);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_2);
            pdfPTable3.addCell(CELDA_INTERMEDIA3_3);
            paragraph.add(pdfPTable3);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableTituInfo = new PdfPTable(1);
            pdfPTableTituInfo.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T1 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T1.setFixedHeight(3);
            PdfPCell CELDA_INTER_T2 = new PdfPCell(new Phrase("2. INFORMACIÓN DEL PROYECTO PRODUCTIVO", fSubTitle));
            CELDA_INTER_T2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T2.setFixedHeight(17);
            CELDA_INTER_T2.setBackgroundColor(new BaseColor(213, 235, 255));//176, 224, 230));
            CELDA_INTER_T2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T2.setVerticalAlignment(Element.ALIGN_MIDDLE);
            CELDA_INTER_T1.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T1.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableTituInfo.addCell(CELDA_INTER_T2);
            pdfPTableTituInfo.addCell(CELDA_INTER_T1);
            paragraph.add(pdfPTableTituInfo);
            document.add(paragraph);
            float[] columnWidthsCUADRO4 = {1.5f, 7.1f, 0.12f};
            paragraph = new Paragraph();
            PdfPTable pdfPTable4 = new PdfPTable(columnWidthsCUADRO4);
            pdfPTable4.setWidthPercentage(108f);
            PdfPCell CELDA_INTERMEDIA4_1 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_2 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_3 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA4_1.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_1.setBorder(Rectangle.LEFT);
            CELDA_INTERMEDIA4_2.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_3.setBorder(Rectangle.RIGHT);
            PdfPCell CELDA_INTERMEDIA4_4 = new PdfPCell(new Phrase("2.1 Tipo de proyecto", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_5 = new PdfPCell(new Phrase(tokens[15], fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_6 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_7 = new PdfPCell(new Phrase("2.2 Título del Proyecto", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_8 = new PdfPCell(new Phrase(tokens[16], fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_9 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_10 = new PdfPCell(new Phrase("2.3 Producto Principal", fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_11 = new PdfPCell(new Phrase(tokens[17], fSubTitle));
            PdfPCell CELDA_INTERMEDIA4_12 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA4_4.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA4_7.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA4_10.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA4_6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_6.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA4_9.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_9.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA4_12.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_12.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA4_1.setFixedHeight(3);
            CELDA_INTERMEDIA4_2.setFixedHeight(3);
            CELDA_INTERMEDIA4_6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA4_6.setBorder(Rectangle.RIGHT);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_4);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_5);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_6);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_1);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_2);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_3);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_7);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_8);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_9);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_1);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_2);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_3);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_10);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_11);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_12);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_1);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_2);
            pdfPTable4.addCell(CELDA_INTERMEDIA4_3);
            paragraph.add(pdfPTable4);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsCUADRO5 = {1.75f, 1.2f, 2.1f, 4.95f, 0.15f};
            PdfPTable pdfPTable5 = new PdfPTable(columnWidthsCUADRO5);
            pdfPTable5.setWidthPercentage(108f);
            PdfPCell CELDA_INTERMEDIA5_1 = new PdfPCell(new Phrase("2.4 Sector Productivo", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_2 = new PdfPCell(new Phrase(tokens[18], fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_3 = new PdfPCell(new Phrase("Descripción Sector", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_4 = new PdfPCell(new Phrase(tokens[19], fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_5 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_6 = new PdfPCell(new Phrase("2.5 Actividad", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_7 = new PdfPCell(new Phrase(tokens[20], fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_8 = new PdfPCell(new Phrase("Descripción Actividad", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_9 = new PdfPCell(new Phrase(tokens[21], fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_10 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_11 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_12 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_13 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_14 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA5_15 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA5_1.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA5_2.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA5_3.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA5_6.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA5_8.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA5_5.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_5.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA5_11.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_11.setBorder(Rectangle.LEFT);
            CELDA_INTERMEDIA5_15.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_15.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA5_12.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_13.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_14.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_10.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA5_10.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA5_11.setFixedHeight(3);
            CELDA_INTERMEDIA5_12.setFixedHeight(3);
            CELDA_INTERMEDIA5_13.setFixedHeight(3);
            CELDA_INTERMEDIA5_14.setFixedHeight(3);
            CELDA_INTERMEDIA5_15.setFixedHeight(3);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_1);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_2);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_3);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_4);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_5);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_11);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_12);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_13);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_14);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_15);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_6);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_7);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_8);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_9);
            pdfPTable5.addCell(CELDA_INTERMEDIA5_10);
            paragraph.add(pdfPTable5);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTable6 = new PdfPTable(columnWidthsCUADRO4);
            pdfPTable6.setWidthPercentage(108f);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_1);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_2);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_3);
            PdfPCell CELDA_INTERMEDIA6_1 = new PdfPCell(new Phrase("2.6 Breve descripción del Proyecto Productivo", fSubTitle));
            PdfPCell CELDA_INTERMEDIA6_2 = new PdfPCell(new Phrase(tokens[22], fSubTitle));
            PdfPCell CELDA_INTERMEDIA6_3 = new PdfPCell(new Phrase("", fSubTitle));
            PdfPCell CELDA_INTERMEDIA6_4 = new PdfPCell(new Phrase("2.7 Oportunidades comerciales", fSubTitle));
            PdfPCell CELDA_INTERMEDIA6_5 = new PdfPCell(new Phrase(tokens[23], fSubTitle));
            PdfPCell CELDA_INTERMEDIA6_6 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTERMEDIA6_1.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA6_4.setBackgroundColor(new BaseColor(205, 205, 205));
            CELDA_INTERMEDIA6_3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA6_3.setBorder(Rectangle.RIGHT);
            CELDA_INTERMEDIA6_6.setBorder(Rectangle.NO_BORDER);
            CELDA_INTERMEDIA6_6.setBorder(Rectangle.RIGHT);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_1);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_2);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_3);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_1);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_2);
            pdfPTable6.addCell(CELDA_INTERMEDIA4_3);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_4);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_5);
            pdfPTable6.addCell(CELDA_INTERMEDIA6_6);
            paragraph.add(pdfPTable6);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableInver = new PdfPTable(1);
            pdfPTableInver.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T3 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T3.setFixedHeight(3);
            PdfPCell CELDA_INTER_T4 = new PdfPCell(new Phrase("3.  INVERSIÓN A REALIZAR\n" +
                    "Diligencie la inversión de acuerdo con las necesidades requeridas en la unidad productiva", fSubTitle));
            CELDA_INTER_T4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T4.setFixedHeight(17);
            CELDA_INTER_T3.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T4.setBackgroundColor(new BaseColor(213, 235, 255));
            CELDA_INTER_T3.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableInver.addCell(CELDA_INTER_T3);
            pdfPTableInver.addCell(CELDA_INTER_T4);
            paragraph.add(pdfPTableInver);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableInver2 = new PdfPTable(1);
            pdfPTableInver2.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T5 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T5.setFixedHeight(3);
            PdfPCell CELDA_INTER_T6 = new PdfPCell(new Phrase("3.1. GASTOS PREOPERATIVOS\nGastos requeridos para iniciar el negocio (adecuaciones de local, servicios públicos, etc.)", fSubTitle));
            CELDA_INTER_T6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T6.setFixedHeight(12);
            CELDA_INTER_T5.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T5.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            CELDA_INTER_T6.setBackgroundColor(new BaseColor(213, 235, 242));
            CELDA_INTER_T6.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableInver2.addCell(CELDA_INTER_T5);
            pdfPTableInver2.addCell(CELDA_INTER_T6);
            pdfPTableInver2.addCell(CELDA_INTER_T5);
            paragraph.add(pdfPTableInver2);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsCUADRO6 = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable table = new PdfPTable(columnWidthsCUADRO6);
            table.setWidthPercentage(108f);
            //     table.setWidths();
            PdfPCell cell;
            cell = new PdfPCell(new Phrase("CONCEPTO", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("CANTIDAD", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("UNIDAD\n DE\n MEDIDA", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("VALOR UNITARIO", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("VALOR TOTAL", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("FUENTE", fSubTitle));
            cell.setColspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            cell = new PdfPCell(new Phrase("Verificación", fSubTitle));
            cell.setRowspan(2);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cell);
            PdfPCell cellPS = new PdfPCell(new Phrase("PS", fSubTitle));
            cellPS.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cellPS.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellPS.setBackgroundColor(new BaseColor(213, 235, 242));
            PdfPCell cellHOGAR = new PdfPCell(new Phrase("HOGAR", fSubTitle));
            cellHOGAR.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cellHOGAR.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellHOGAR.setBackgroundColor(new BaseColor(213, 235, 242));
            table.addCell(cellPS);
            table.addCell(cellHOGAR);
            document.add(table);
            paragraph = new Paragraph();
            float[] columnWidthsGP = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable pdfPTableGP = new PdfPTable(columnWidthsGP);
            pdfPTableGP.setWidthPercentage(108f);
            PdfPCell CELDA_GP_1_1 = new PdfPCell(new Phrase(tokens[26], fNormal));
            PdfPCell CELDA_GP_1_2 = new PdfPCell(new Phrase(tokens[27], fNormal));
            PdfPCell CELDA_GP_1_3 = new PdfPCell(new Phrase(tokens[28], fNormal));
            PdfPCell CELDA_GP_1_4 = new PdfPCell(new Phrase(tokens[29], fNormal));
            PdfPCell CELDA_GP_1_5 = new PdfPCell(new Phrase(tokens[30], fNormal));
            PdfPCell CELDA_GP_1_6 = new PdfPCell(new Phrase(tokens[31], fNormal));
            PdfPCell CELDA_GP_1_7 = new PdfPCell(new Phrase(tokens[32], fNormal));
            PdfPCell CELDA_GP_1_8 = new PdfPCell(new Phrase("Cumple", fNormal));
            PdfPCell CELDA_GP_2_1 = new PdfPCell(new Phrase(tokens[33], fNormal));
            PdfPCell CELDA_GP_2_2 = new PdfPCell(new Phrase(tokens[34], fNormal));
            PdfPCell CELDA_GP_2_3 = new PdfPCell(new Phrase(tokens[35], fNormal));
            PdfPCell CELDA_GP_2_4 = new PdfPCell(new Phrase(tokens[36], fNormal));
            PdfPCell CELDA_GP_2_5 = new PdfPCell(new Phrase(tokens[37], fNormal));
            PdfPCell CELDA_GP_2_6 = new PdfPCell(new Phrase(tokens[38], fNormal));
            PdfPCell CELDA_GP_2_7 = new PdfPCell(new Phrase(tokens[39], fNormal));
            PdfPCell CELDA_GP_2_8 = new PdfPCell(new Phrase("Cumple", fNormal));
            PdfPCell CELDA_GP_3_1 = new PdfPCell(new Phrase("A1", fNormal));
            PdfPCell CELDA_GP_3_2 = new PdfPCell(new Phrase("A2", fNormal));
            PdfPCell CELDA_GP_3_3 = new PdfPCell(new Phrase("A3", fNormal));
            PdfPCell CELDA_GP_3_4 = new PdfPCell(new Phrase("A4", fNormal));
            PdfPCell CELDA_GP_3_5 = new PdfPCell(new Phrase("A5", fNormal));
            PdfPCell CELDA_GP_3_6 = new PdfPCell(new Phrase("A6", fNormal));
            PdfPCell CELDA_GP_3_7 = new PdfPCell(new Phrase("A7", fNormal));
            PdfPCell CELDA_GP_3_8 = new PdfPCell(new Phrase("A8", fNormal));
            PdfPCell CELDA_GP_4_1 = new PdfPCell(new Phrase("A1", fNormal));
            PdfPCell CELDA_GP_4_2 = new PdfPCell(new Phrase("A2", fNormal));
            PdfPCell CELDA_GP_4_3 = new PdfPCell(new Phrase("A3", fNormal));
            PdfPCell CELDA_GP_4_4 = new PdfPCell(new Phrase("A4", fNormal));
            PdfPCell CELDA_GP_4_5 = new PdfPCell(new Phrase("A5", fNormal));
            PdfPCell CELDA_GP_4_6 = new PdfPCell(new Phrase("A6", fNormal));
            PdfPCell CELDA_GP_4_7 = new PdfPCell(new Phrase("A7", fNormal));
            PdfPCell CELDA_GP_4_8 = new PdfPCell(new Phrase("A8", fNormal));
            PdfPCell CELDA_GP_5_1 = new PdfPCell(new Phrase("A1", fNormal));
            PdfPCell CELDA_GP_5_2 = new PdfPCell(new Phrase("A2", fNormal));
            PdfPCell CELDA_GP_5_3 = new PdfPCell(new Phrase("A3", fNormal));
            PdfPCell CELDA_GP_5_4 = new PdfPCell(new Phrase("A4", fNormal));
            PdfPCell CELDA_GP_5_5 = new PdfPCell(new Phrase("A5", fNormal));
            PdfPCell CELDA_GP_5_6 = new PdfPCell(new Phrase("A6", fNormal));
            PdfPCell CELDA_GP_5_7 = new PdfPCell(new Phrase("A7", fNormal));
            PdfPCell CELDA_GP_5_8 = new PdfPCell(new Phrase("A8", fNormal));
            PdfPCell CELDA_GP_6_1 = new PdfPCell(new Phrase("A1", fNormal));
            PdfPCell CELDA_GP_6_2 = new PdfPCell(new Phrase("A2", fNormal));
            PdfPCell CELDA_GP_6_3 = new PdfPCell(new Phrase("A3", fNormal));
            PdfPCell CELDA_GP_6_4 = new PdfPCell(new Phrase("A4", fNormal));
            PdfPCell CELDA_GP_6_5 = new PdfPCell(new Phrase("A5", fNormal));
            PdfPCell CELDA_GP_6_6 = new PdfPCell(new Phrase("A6", fNormal));
            PdfPCell CELDA_GP_6_7 = new PdfPCell(new Phrase("A7", fNormal));
            PdfPCell CELDA_GP_6_8 = new PdfPCell(new Phrase("A8", fNormal));
            CELDA_GP_1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_1_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_2_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_3_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_4_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_5_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_GP_6_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPTableGP.addCell(CELDA_GP_1_1);
            pdfPTableGP.addCell(CELDA_GP_1_2);
            pdfPTableGP.addCell(CELDA_GP_1_3);
            pdfPTableGP.addCell(CELDA_GP_1_4);
            pdfPTableGP.addCell(CELDA_GP_1_5);
            pdfPTableGP.addCell(CELDA_GP_1_6);
            pdfPTableGP.addCell(CELDA_GP_1_7);
            pdfPTableGP.addCell(CELDA_GP_1_8);
            pdfPTableGP.addCell(CELDA_GP_2_1);
            pdfPTableGP.addCell(CELDA_GP_2_2);
            pdfPTableGP.addCell(CELDA_GP_2_3);
            pdfPTableGP.addCell(CELDA_GP_2_4);
            pdfPTableGP.addCell(CELDA_GP_2_5);
            pdfPTableGP.addCell(CELDA_GP_2_6);
            pdfPTableGP.addCell(CELDA_GP_2_7);
            pdfPTableGP.addCell(CELDA_GP_2_8);
            pdfPTableGP.addCell(CELDA_GP_3_1);
            pdfPTableGP.addCell(CELDA_GP_3_2);
            pdfPTableGP.addCell(CELDA_GP_3_3);
            pdfPTableGP.addCell(CELDA_GP_3_4);
            pdfPTableGP.addCell(CELDA_GP_3_5);
            pdfPTableGP.addCell(CELDA_GP_3_6);
            pdfPTableGP.addCell(CELDA_GP_3_7);
            pdfPTableGP.addCell(CELDA_GP_3_8);
            pdfPTableGP.addCell(CELDA_GP_4_1);
            pdfPTableGP.addCell(CELDA_GP_4_2);
            pdfPTableGP.addCell(CELDA_GP_4_3);
            pdfPTableGP.addCell(CELDA_GP_4_4);
            pdfPTableGP.addCell(CELDA_GP_4_5);
            pdfPTableGP.addCell(CELDA_GP_4_6);
            pdfPTableGP.addCell(CELDA_GP_4_7);
            pdfPTableGP.addCell(CELDA_GP_4_8);
            pdfPTableGP.addCell(CELDA_GP_5_1);
            pdfPTableGP.addCell(CELDA_GP_5_2);
            pdfPTableGP.addCell(CELDA_GP_5_3);
            pdfPTableGP.addCell(CELDA_GP_5_4);
            pdfPTableGP.addCell(CELDA_GP_5_5);
            pdfPTableGP.addCell(CELDA_GP_5_6);
            pdfPTableGP.addCell(CELDA_GP_5_7);
            pdfPTableGP.addCell(CELDA_GP_5_8);
            pdfPTableGP.addCell(CELDA_GP_6_1);
            pdfPTableGP.addCell(CELDA_GP_6_2);
            pdfPTableGP.addCell(CELDA_GP_6_3);
            pdfPTableGP.addCell(CELDA_GP_6_4);
            pdfPTableGP.addCell(CELDA_GP_6_5);
            pdfPTableGP.addCell(CELDA_GP_6_6);
            pdfPTableGP.addCell(CELDA_GP_6_7);
            pdfPTableGP.addCell(CELDA_GP_6_8);
            paragraph.add(pdfPTableGP);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsTotal = {6.82f, 2.225f, 1.775f, 1.63f, 1.48f};
            PdfPTable pdfPTableTotal = new PdfPTable(columnWidthsTotal);
            pdfPTableTotal.setWidthPercentage(108f);
            PdfPCell CELDA_GP_Ti_Total = new PdfPCell(new Phrase("TOTAL", fSubTitle));
            PdfPCell CELDA_GP_Total = new PdfPCell(new Phrase("1234", fSubTitle));
            PdfPCell CELDA_GP_ps = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_GP_hogar = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_GP_Veri = new PdfPCell(new Phrase("-", fNormal));
            pdfPTableTotal.addCell(CELDA_GP_Ti_Total);
            pdfPTableTotal.addCell(CELDA_GP_Total);
            pdfPTableTotal.addCell(CELDA_GP_ps);
            pdfPTableTotal.addCell(CELDA_GP_hogar);
            pdfPTableTotal.addCell(CELDA_GP_Veri);
            paragraph.add(pdfPTableTotal);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableT2 = new PdfPTable(1);
            pdfPTableT2.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T7 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T7.setFixedHeight(3);
            PdfPCell CELDA_INTER_T8 = new PdfPCell(new Phrase("3.2 CAPITAL DE TRABAJO ", fSubTitle));
            CELDA_INTER_T8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T7.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T7.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            CELDA_INTER_T8.setFixedHeight(12);
            CELDA_INTER_T8.setBackgroundColor(new BaseColor(213, 235, 242));
            CELDA_INTER_T8.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableT2.addCell(CELDA_INTER_T7);
            pdfPTableT2.addCell(CELDA_INTER_T8);
            pdfPTableT2.addCell(CELDA_INTER_T7);
            paragraph.add(pdfPTableT2);
            document.add(paragraph);
            document.add(table);
            paragraph = new Paragraph();
            float[] columnWidthsCT = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable pdfPTableCT = new PdfPTable(columnWidthsCT);
            pdfPTableCT.setWidthPercentage(108f);
            PdfPCell CELDA_CT_1_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_1_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_1_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_1_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_1_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_1_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_1_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_1_8 = new PdfPCell(new Phrase("CT8", fNormal));
            PdfPCell CELDA_CT_2_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_2_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_2_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_2_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_2_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_2_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_2_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_2_8 = new PdfPCell(new Phrase("CT8", fNormal));
            PdfPCell CELDA_CT_3_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_3_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_3_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_3_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_3_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_3_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_3_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_3_8 = new PdfPCell(new Phrase("CT8", fNormal));
            PdfPCell CELDA_CT_4_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_4_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_4_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_4_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_4_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_4_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_4_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_4_8 = new PdfPCell(new Phrase("CT8", fNormal));
            PdfPCell CELDA_CT_5_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_5_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_5_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_5_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_5_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_5_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_5_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_5_8 = new PdfPCell(new Phrase("CT8", fNormal));
            PdfPCell CELDA_CT_6_1 = new PdfPCell(new Phrase("CT1", fNormal));
            PdfPCell CELDA_CT_6_2 = new PdfPCell(new Phrase("CT2", fNormal));
            PdfPCell CELDA_CT_6_3 = new PdfPCell(new Phrase("CT3", fNormal));
            PdfPCell CELDA_CT_6_4 = new PdfPCell(new Phrase("CT4", fNormal));
            PdfPCell CELDA_CT_6_5 = new PdfPCell(new Phrase("CT5", fNormal));
            PdfPCell CELDA_CT_6_6 = new PdfPCell(new Phrase("CT6", fNormal));
            PdfPCell CELDA_CT_6_7 = new PdfPCell(new Phrase("CT7", fNormal));
            PdfPCell CELDA_CT_6_8 = new PdfPCell(new Phrase("CT8", fNormal));
            CELDA_CT_1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_1_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_2_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_3_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_4_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_5_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_CT_6_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPTableCT.addCell(CELDA_CT_1_1);
            pdfPTableCT.addCell(CELDA_CT_1_2);
            pdfPTableCT.addCell(CELDA_CT_1_3);
            pdfPTableCT.addCell(CELDA_CT_1_4);
            pdfPTableCT.addCell(CELDA_CT_1_5);
            pdfPTableCT.addCell(CELDA_CT_1_6);
            pdfPTableCT.addCell(CELDA_CT_1_7);
            pdfPTableCT.addCell(CELDA_CT_1_8);
            pdfPTableCT.addCell(CELDA_CT_2_1);
            pdfPTableCT.addCell(CELDA_CT_2_2);
            pdfPTableCT.addCell(CELDA_CT_2_3);
            pdfPTableCT.addCell(CELDA_CT_2_4);
            pdfPTableCT.addCell(CELDA_CT_2_5);
            pdfPTableCT.addCell(CELDA_CT_2_6);
            pdfPTableCT.addCell(CELDA_CT_2_7);
            pdfPTableCT.addCell(CELDA_CT_2_8);
            pdfPTableCT.addCell(CELDA_CT_3_1);
            pdfPTableCT.addCell(CELDA_CT_3_2);
            pdfPTableCT.addCell(CELDA_CT_3_3);
            pdfPTableCT.addCell(CELDA_CT_3_4);
            pdfPTableCT.addCell(CELDA_CT_3_5);
            pdfPTableCT.addCell(CELDA_CT_3_6);
            pdfPTableCT.addCell(CELDA_CT_3_7);
            pdfPTableCT.addCell(CELDA_CT_3_8);
            pdfPTableCT.addCell(CELDA_CT_4_1);
            pdfPTableCT.addCell(CELDA_CT_4_2);
            pdfPTableCT.addCell(CELDA_CT_4_3);
            pdfPTableCT.addCell(CELDA_CT_4_4);
            pdfPTableCT.addCell(CELDA_CT_4_5);
            pdfPTableCT.addCell(CELDA_CT_4_6);
            pdfPTableCT.addCell(CELDA_CT_4_7);
            pdfPTableCT.addCell(CELDA_CT_4_8);
            pdfPTableCT.addCell(CELDA_CT_5_1);
            pdfPTableCT.addCell(CELDA_CT_5_2);
            pdfPTableCT.addCell(CELDA_CT_5_3);
            pdfPTableCT.addCell(CELDA_CT_5_4);
            pdfPTableCT.addCell(CELDA_CT_5_5);
            pdfPTableCT.addCell(CELDA_CT_5_6);
            pdfPTableCT.addCell(CELDA_CT_5_7);
            pdfPTableCT.addCell(CELDA_CT_5_8);
            pdfPTableCT.addCell(CELDA_CT_6_1);
            pdfPTableCT.addCell(CELDA_CT_6_2);
            pdfPTableCT.addCell(CELDA_CT_6_3);
            pdfPTableCT.addCell(CELDA_CT_6_4);
            pdfPTableCT.addCell(CELDA_CT_6_5);
            pdfPTableCT.addCell(CELDA_CT_6_6);
            pdfPTableCT.addCell(CELDA_CT_6_7);
            pdfPTableCT.addCell(CELDA_CT_6_8);
            paragraph.add(pdfPTableCT);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsTotalCT = {6.82f, 2.225f, 1.775f, 1.63f, 1.48f};
            PdfPTable pdfPTableTotalCT = new PdfPTable(columnWidthsTotalCT);
            pdfPTableTotalCT.setWidthPercentage(108f);
            PdfPCell CELDA_CT_Ti_Total = new PdfPCell(new Phrase("TOTAL", fSubTitle));
            PdfPCell CELDA_CT_Total = new PdfPCell(new Phrase("1234", fSubTitle));
            PdfPCell CELDA_CT_ps = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_CT_hogar = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_CT_Veri = new PdfPCell(new Phrase("-", fNormal));
            pdfPTableTotalCT.addCell(CELDA_CT_Ti_Total);
            pdfPTableTotalCT.addCell(CELDA_CT_Total);
            pdfPTableTotalCT.addCell(CELDA_CT_ps);
            pdfPTableTotalCT.addCell(CELDA_CT_hogar);
            pdfPTableTotalCT.addCell(CELDA_CT_Veri);
            paragraph.add(pdfPTableTotalCT);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableT3 = new PdfPTable(1);
            pdfPTableT3.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T9 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T9.setFixedHeight(3);
            PdfPCell CELDA_INTER_T10 = new PdfPCell(new Phrase("3.3. ACTIVOS FIJOS \n" +
                    "(maquinaria y herramientas, mobiliario, equipos, empaques)", fSubTitle));
            CELDA_INTER_T10.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T9.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T9.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            CELDA_INTER_T10.setFixedHeight(12);
            CELDA_INTER_T10.setBackgroundColor(new BaseColor(213, 235, 242));
            CELDA_INTER_T10.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableT3.addCell(CELDA_INTER_T9);
            pdfPTableT3.addCell(CELDA_INTER_T10);
            pdfPTableT3.addCell(CELDA_INTER_T9);
            paragraph.add(pdfPTableT3);
            document.add(paragraph);
            document.add(table);
            paragraph = new Paragraph();
            float[] columnWidthsAF = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable pdfPTableAF = new PdfPTable(columnWidthsAF);
            pdfPTableAF.setWidthPercentage(108f);
            PdfPCell CELDA_AF_1_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_1_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_1_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_1_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_1_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_1_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_1_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_1_8 = new PdfPCell(new Phrase("AF8", fNormal));
            PdfPCell CELDA_AF_2_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_2_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_2_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_2_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_2_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_2_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_2_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_2_8 = new PdfPCell(new Phrase("AF8", fNormal));
            PdfPCell CELDA_AF_3_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_3_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_3_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_3_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_3_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_3_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_3_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_3_8 = new PdfPCell(new Phrase("AF8", fNormal));
            PdfPCell CELDA_AF_4_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_4_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_4_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_4_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_4_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_4_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_4_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_4_8 = new PdfPCell(new Phrase("AF8", fNormal));
            PdfPCell CELDA_AF_5_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_5_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_5_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_5_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_5_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_5_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_5_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_5_8 = new PdfPCell(new Phrase("AF8", fNormal));
            PdfPCell CELDA_AF_6_1 = new PdfPCell(new Phrase("AF1", fNormal));
            PdfPCell CELDA_AF_6_2 = new PdfPCell(new Phrase("AF2", fNormal));
            PdfPCell CELDA_AF_6_3 = new PdfPCell(new Phrase("AF3", fNormal));
            PdfPCell CELDA_AF_6_4 = new PdfPCell(new Phrase("AF4", fNormal));
            PdfPCell CELDA_AF_6_5 = new PdfPCell(new Phrase("AF5", fNormal));
            PdfPCell CELDA_AF_6_6 = new PdfPCell(new Phrase("AF6", fNormal));
            PdfPCell CELDA_AF_6_7 = new PdfPCell(new Phrase("AF7", fNormal));
            PdfPCell CELDA_AF_6_8 = new PdfPCell(new Phrase("AF8", fNormal));
            CELDA_AF_1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_1_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_2_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_3_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_4_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_5_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_AF_6_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPTableAF.addCell(CELDA_AF_1_1);
            pdfPTableAF.addCell(CELDA_AF_1_2);
            pdfPTableAF.addCell(CELDA_AF_1_3);
            pdfPTableAF.addCell(CELDA_AF_1_4);
            pdfPTableAF.addCell(CELDA_AF_1_5);
            pdfPTableAF.addCell(CELDA_AF_1_6);
            pdfPTableAF.addCell(CELDA_AF_1_7);
            pdfPTableAF.addCell(CELDA_AF_1_8);
            pdfPTableAF.addCell(CELDA_AF_2_1);
            pdfPTableAF.addCell(CELDA_AF_2_2);
            pdfPTableAF.addCell(CELDA_AF_2_3);
            pdfPTableAF.addCell(CELDA_AF_2_4);
            pdfPTableAF.addCell(CELDA_AF_2_5);
            pdfPTableAF.addCell(CELDA_AF_2_6);
            pdfPTableAF.addCell(CELDA_AF_2_7);
            pdfPTableAF.addCell(CELDA_AF_2_8);
            pdfPTableAF.addCell(CELDA_AF_3_1);
            pdfPTableAF.addCell(CELDA_AF_3_2);
            pdfPTableAF.addCell(CELDA_AF_3_3);
            pdfPTableAF.addCell(CELDA_AF_3_4);
            pdfPTableAF.addCell(CELDA_AF_3_5);
            pdfPTableAF.addCell(CELDA_AF_3_6);
            pdfPTableAF.addCell(CELDA_AF_3_7);
            pdfPTableAF.addCell(CELDA_AF_3_8);
            pdfPTableAF.addCell(CELDA_AF_4_1);
            pdfPTableAF.addCell(CELDA_AF_4_2);
            pdfPTableAF.addCell(CELDA_AF_4_3);
            pdfPTableAF.addCell(CELDA_AF_4_4);
            pdfPTableAF.addCell(CELDA_AF_4_5);
            pdfPTableAF.addCell(CELDA_AF_4_6);
            pdfPTableAF.addCell(CELDA_AF_4_7);
            pdfPTableAF.addCell(CELDA_AF_4_8);
            pdfPTableAF.addCell(CELDA_AF_5_1);
            pdfPTableAF.addCell(CELDA_AF_5_2);
            pdfPTableAF.addCell(CELDA_AF_5_3);
            pdfPTableAF.addCell(CELDA_AF_5_4);
            pdfPTableAF.addCell(CELDA_AF_5_5);
            pdfPTableAF.addCell(CELDA_AF_5_6);
            pdfPTableAF.addCell(CELDA_AF_5_7);
            pdfPTableAF.addCell(CELDA_AF_5_8);
            pdfPTableAF.addCell(CELDA_AF_6_1);
            pdfPTableAF.addCell(CELDA_AF_6_2);
            pdfPTableAF.addCell(CELDA_AF_6_3);
            pdfPTableAF.addCell(CELDA_AF_6_4);
            pdfPTableAF.addCell(CELDA_AF_6_5);
            pdfPTableAF.addCell(CELDA_AF_6_6);
            pdfPTableAF.addCell(CELDA_AF_6_7);
            pdfPTableAF.addCell(CELDA_AF_6_8);
            paragraph.add(pdfPTableAF);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsTotalAF = {6.82f, 2.225f, 1.775f, 1.63f, 1.48f};
            PdfPTable pdfPTableTotalAF = new PdfPTable(columnWidthsTotalAF);
            pdfPTableTotalAF.setWidthPercentage(108f);
            PdfPCell CELDA_AF_Ti_Total = new PdfPCell(new Phrase("TOTAL", fSubTitle));
            PdfPCell CELDA_AF_Total = new PdfPCell(new Phrase("1234", fSubTitle));
            PdfPCell CELDA_AF_ps = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_AF_hogar = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_AF_Veri = new PdfPCell(new Phrase("-", fNormal));
            pdfPTableTotalAF.addCell(CELDA_AF_Ti_Total);
            pdfPTableTotalAF.addCell(CELDA_AF_Total);
            pdfPTableTotalAF.addCell(CELDA_AF_ps);
            pdfPTableTotalAF.addCell(CELDA_AF_hogar);
            pdfPTableTotalAF.addCell(CELDA_AF_Veri);
            paragraph.add(pdfPTableTotalAF);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableT4 = new PdfPTable(1);
            pdfPTableT4.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T11 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T11.setFixedHeight(3);
            PdfPCell CELDA_INTER_T12 = new PdfPCell(new Phrase("3.4. MERCADEO\nElementos que faciliten el mercadeo del bien o servicio (avisos, volantes, tarjetas, portafolio, etc)", fSubTitle));
            CELDA_INTER_T12.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T11.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T11.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            CELDA_INTER_T12.setFixedHeight(12);
            CELDA_INTER_T12.setBackgroundColor(new BaseColor(213, 235, 242));
            CELDA_INTER_T12.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableT4.addCell(CELDA_INTER_T11);
            pdfPTableT4.addCell(CELDA_INTER_T12);
            pdfPTableT4.addCell(CELDA_INTER_T11);
            paragraph.add(pdfPTableT4);
            document.add(paragraph);
            document.add(table);
            paragraph = new Paragraph();
            float[] columnWidthsMER = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable pdfPTableMER = new PdfPTable(columnWidthsMER);
            pdfPTableMER.setWidthPercentage(108f);
            PdfPCell CELDA_MER_1_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_1_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_1_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_1_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_1_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_1_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_1_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_1_8 = new PdfPCell(new Phrase("MER8", fNormal));
            PdfPCell CELDA_MER_2_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_2_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_2_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_2_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_2_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_2_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_2_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_2_8 = new PdfPCell(new Phrase("MER8", fNormal));
            PdfPCell CELDA_MER_3_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_3_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_3_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_3_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_3_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_3_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_3_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_3_8 = new PdfPCell(new Phrase("MER8", fNormal));
            PdfPCell CELDA_MER_4_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_4_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_4_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_4_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_4_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_4_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_4_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_4_8 = new PdfPCell(new Phrase("MER8", fNormal));
            PdfPCell CELDA_MER_5_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_5_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_5_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_5_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_5_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_5_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_5_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_5_8 = new PdfPCell(new Phrase("MER8", fNormal));
            PdfPCell CELDA_MER_6_1 = new PdfPCell(new Phrase("MER1", fNormal));
            PdfPCell CELDA_MER_6_2 = new PdfPCell(new Phrase("MER2", fNormal));
            PdfPCell CELDA_MER_6_3 = new PdfPCell(new Phrase("MER3", fNormal));
            PdfPCell CELDA_MER_6_4 = new PdfPCell(new Phrase("MER4", fNormal));
            PdfPCell CELDA_MER_6_5 = new PdfPCell(new Phrase("MER5", fNormal));
            PdfPCell CELDA_MER_6_6 = new PdfPCell(new Phrase("MER6", fNormal));
            PdfPCell CELDA_MER_6_7 = new PdfPCell(new Phrase("MER7", fNormal));
            PdfPCell CELDA_MER_6_8 = new PdfPCell(new Phrase("MER8", fNormal));
            CELDA_MER_1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_1_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_2_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_3_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_4_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_5_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_MER_6_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPTableMER.addCell(CELDA_MER_1_1);
            pdfPTableMER.addCell(CELDA_MER_1_2);
            pdfPTableMER.addCell(CELDA_MER_1_3);
            pdfPTableMER.addCell(CELDA_MER_1_4);
            pdfPTableMER.addCell(CELDA_MER_1_5);
            pdfPTableMER.addCell(CELDA_MER_1_6);
            pdfPTableMER.addCell(CELDA_MER_1_7);
            pdfPTableMER.addCell(CELDA_MER_1_8);
            pdfPTableMER.addCell(CELDA_MER_2_1);
            pdfPTableMER.addCell(CELDA_MER_2_2);
            pdfPTableMER.addCell(CELDA_MER_2_3);
            pdfPTableMER.addCell(CELDA_MER_2_4);
            pdfPTableMER.addCell(CELDA_MER_2_5);
            pdfPTableMER.addCell(CELDA_MER_2_6);
            pdfPTableMER.addCell(CELDA_MER_2_7);
            pdfPTableMER.addCell(CELDA_MER_2_8);
            pdfPTableMER.addCell(CELDA_MER_3_1);
            pdfPTableMER.addCell(CELDA_MER_3_2);
            pdfPTableMER.addCell(CELDA_MER_3_3);
            pdfPTableMER.addCell(CELDA_MER_3_4);
            pdfPTableMER.addCell(CELDA_MER_3_5);
            pdfPTableMER.addCell(CELDA_MER_3_6);
            pdfPTableMER.addCell(CELDA_MER_3_7);
            pdfPTableMER.addCell(CELDA_MER_3_8);
            pdfPTableMER.addCell(CELDA_MER_4_1);
            pdfPTableMER.addCell(CELDA_MER_4_2);
            pdfPTableMER.addCell(CELDA_MER_4_3);
            pdfPTableMER.addCell(CELDA_MER_4_4);
            pdfPTableMER.addCell(CELDA_MER_4_5);
            pdfPTableMER.addCell(CELDA_MER_4_6);
            pdfPTableMER.addCell(CELDA_MER_4_7);
            pdfPTableMER.addCell(CELDA_MER_4_8);
            pdfPTableMER.addCell(CELDA_MER_5_1);
            pdfPTableMER.addCell(CELDA_MER_5_2);
            pdfPTableMER.addCell(CELDA_MER_5_3);
            pdfPTableMER.addCell(CELDA_MER_5_4);
            pdfPTableMER.addCell(CELDA_MER_5_5);
            pdfPTableMER.addCell(CELDA_MER_5_6);
            pdfPTableMER.addCell(CELDA_MER_5_7);
            pdfPTableMER.addCell(CELDA_MER_5_8);
            pdfPTableMER.addCell(CELDA_MER_6_1);
            pdfPTableMER.addCell(CELDA_MER_6_2);
            pdfPTableMER.addCell(CELDA_MER_6_3);
            pdfPTableMER.addCell(CELDA_MER_6_4);
            pdfPTableMER.addCell(CELDA_MER_6_5);
            pdfPTableMER.addCell(CELDA_MER_6_6);
            pdfPTableMER.addCell(CELDA_MER_6_7);
            pdfPTableMER.addCell(CELDA_MER_6_8);
            paragraph.add(pdfPTableMER);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsTotalMER = {6.82f, 2.225f, 1.775f, 1.63f, 1.48f};
            PdfPTable pdfPTableTotalMER = new PdfPTable(columnWidthsTotalMER);
            pdfPTableTotalMER.setWidthPercentage(108f);
            PdfPCell CELDA_MER_Ti_Total = new PdfPCell(new Phrase("TOTAL", fSubTitle));
            PdfPCell CELDA_MER_Total = new PdfPCell(new Phrase("1234", fSubTitle));
            PdfPCell CELDA_MER_ps = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_MER_hogar = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_MER_Veri = new PdfPCell(new Phrase("-", fNormal));
            pdfPTableTotalMER.addCell(CELDA_MER_Ti_Total);
            pdfPTableTotalMER.addCell(CELDA_MER_Total);
            pdfPTableTotalMER.addCell(CELDA_MER_ps);
            pdfPTableTotalMER.addCell(CELDA_MER_hogar);
            pdfPTableTotalMER.addCell(CELDA_MER_Veri);
            paragraph.add(pdfPTableTotalMER);
            document.add(paragraph);
            paragraph = new Paragraph();
            PdfPTable pdfPTableT5 = new PdfPTable(1);
            pdfPTableT5.setWidthPercentage(108f);
            PdfPCell CELDA_INTER_T13 = new PdfPCell(new Phrase("", fSubTitle));
            CELDA_INTER_T13.setFixedHeight(3);
            PdfPCell CELDA_INTER_T14 = new PdfPCell(new Phrase("3.5. SEGURIDAD EN EL TRABAJO\nElementos para el cuidado del personal y del medio ambiente", fSubTitle));
            CELDA_INTER_T14.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_INTER_T13.setBorder(Rectangle.NO_BORDER);
            CELDA_INTER_T13.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            CELDA_INTER_T14.setFixedHeight(12);
            CELDA_INTER_T14.setBackgroundColor(new BaseColor(213, 235, 242));
            CELDA_INTER_T14.setBorder(Rectangle.LEFT | Rectangle.RIGHT);
            pdfPTableT5.addCell(CELDA_INTER_T13);
            pdfPTableT5.addCell(CELDA_INTER_T14);
            pdfPTableT5.addCell(CELDA_INTER_T13);
            paragraph.add(pdfPTableT5);
            document.add(paragraph);
            document.add(table);
            paragraph = new Paragraph();
            float[] columnWidthsST = {3.4f, 1.6f, 1.7f, 2.5f, 3f, 2.4f, 2.2f, 2f};
            PdfPTable pdfPTableST = new PdfPTable(columnWidthsST);
            pdfPTableST.setWidthPercentage(108f);
            PdfPCell CELDA_ST_1_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_1_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_1_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_1_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_1_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_1_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_1_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_1_8 = new PdfPCell(new Phrase("ST8", fNormal));
            PdfPCell CELDA_ST_2_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_2_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_2_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_2_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_2_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_2_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_2_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_2_8 = new PdfPCell(new Phrase("ST8", fNormal));
            PdfPCell CELDA_ST_3_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_3_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_3_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_3_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_3_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_3_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_3_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_3_8 = new PdfPCell(new Phrase("ST8", fNormal));
            PdfPCell CELDA_ST_4_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_4_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_4_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_4_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_4_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_4_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_4_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_4_8 = new PdfPCell(new Phrase("ST8", fNormal));
            PdfPCell CELDA_ST_5_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_5_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_5_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_5_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_5_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_5_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_5_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_5_8 = new PdfPCell(new Phrase("ST8", fNormal));
            PdfPCell CELDA_ST_6_1 = new PdfPCell(new Phrase("ST1", fNormal));
            PdfPCell CELDA_ST_6_2 = new PdfPCell(new Phrase("ST2", fNormal));
            PdfPCell CELDA_ST_6_3 = new PdfPCell(new Phrase("ST3", fNormal));
            PdfPCell CELDA_ST_6_4 = new PdfPCell(new Phrase("ST4", fNormal));
            PdfPCell CELDA_ST_6_5 = new PdfPCell(new Phrase("ST5", fNormal));
            PdfPCell CELDA_ST_6_6 = new PdfPCell(new Phrase("ST6", fNormal));
            PdfPCell CELDA_ST_6_7 = new PdfPCell(new Phrase("ST7", fNormal));
            PdfPCell CELDA_ST_6_8 = new PdfPCell(new Phrase("ST8", fNormal));
            CELDA_ST_1_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_1_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_2_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_3_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_4_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_5_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_1.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_2.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_3.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_4.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_5.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_6.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_7.setHorizontalAlignment(Element.ALIGN_CENTER);
            CELDA_ST_6_8.setHorizontalAlignment(Element.ALIGN_CENTER);
            pdfPTableST.addCell(CELDA_ST_1_1);
            pdfPTableST.addCell(CELDA_ST_1_2);
            pdfPTableST.addCell(CELDA_ST_1_3);
            pdfPTableST.addCell(CELDA_ST_1_4);
            pdfPTableST.addCell(CELDA_ST_1_5);
            pdfPTableST.addCell(CELDA_ST_1_6);
            pdfPTableST.addCell(CELDA_ST_1_7);
            pdfPTableST.addCell(CELDA_ST_1_8);
            pdfPTableST.addCell(CELDA_ST_2_1);
            pdfPTableST.addCell(CELDA_ST_2_2);
            pdfPTableST.addCell(CELDA_ST_2_3);
            pdfPTableST.addCell(CELDA_ST_2_4);
            pdfPTableST.addCell(CELDA_ST_2_5);
            pdfPTableST.addCell(CELDA_ST_2_6);
            pdfPTableST.addCell(CELDA_ST_2_7);
            pdfPTableST.addCell(CELDA_ST_2_8);
            pdfPTableST.addCell(CELDA_ST_3_1);
            pdfPTableST.addCell(CELDA_ST_3_2);
            pdfPTableST.addCell(CELDA_ST_3_3);
            pdfPTableST.addCell(CELDA_ST_3_4);
            pdfPTableST.addCell(CELDA_ST_3_5);
            pdfPTableST.addCell(CELDA_ST_3_6);
            pdfPTableST.addCell(CELDA_ST_3_7);
            pdfPTableST.addCell(CELDA_ST_3_8);
            pdfPTableST.addCell(CELDA_ST_4_1);
            pdfPTableST.addCell(CELDA_ST_4_2);
            pdfPTableST.addCell(CELDA_ST_4_3);
            pdfPTableST.addCell(CELDA_ST_4_4);
            pdfPTableST.addCell(CELDA_ST_4_5);
            pdfPTableST.addCell(CELDA_ST_4_6);
            pdfPTableST.addCell(CELDA_ST_4_7);
            pdfPTableST.addCell(CELDA_ST_4_8);
            pdfPTableST.addCell(CELDA_ST_5_1);
            pdfPTableST.addCell(CELDA_ST_5_2);
            pdfPTableST.addCell(CELDA_ST_5_3);
            pdfPTableST.addCell(CELDA_ST_5_4);
            pdfPTableST.addCell(CELDA_ST_5_5);
            pdfPTableST.addCell(CELDA_ST_5_6);
            pdfPTableST.addCell(CELDA_ST_5_7);
            pdfPTableST.addCell(CELDA_ST_5_8);
            pdfPTableST.addCell(CELDA_ST_6_1);
            pdfPTableST.addCell(CELDA_ST_6_2);
            pdfPTableST.addCell(CELDA_ST_6_3);
            pdfPTableST.addCell(CELDA_ST_6_4);
            pdfPTableST.addCell(CELDA_ST_6_5);
            pdfPTableST.addCell(CELDA_ST_6_6);
            pdfPTableST.addCell(CELDA_ST_6_7);
            pdfPTableST.addCell(CELDA_ST_6_8);
            paragraph.add(pdfPTableST);
            document.add(paragraph);
            paragraph = new Paragraph();
            float[] columnWidthsTotalST = {6.82f, 2.225f, 1.775f, 1.63f, 1.48f};
            PdfPTable pdfPTableTotalST = new PdfPTable(columnWidthsTotalST);
            pdfPTableTotalST.setWidthPercentage(108f);
            PdfPCell CELDA_ST_Ti_Total = new PdfPCell(new Phrase("TOTAL", fSubTitle));
            PdfPCell CELDA_ST_Total = new PdfPCell(new Phrase("1234", fSubTitle));
            PdfPCell CELDA_ST_ps = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_ST_hogar = new PdfPCell(new Phrase("-", fNormal));
            PdfPCell CELDA_ST_Veri = new PdfPCell(new Phrase("-", fNormal));
            pdfPTableTotalST.addCell(CELDA_ST_Ti_Total);
            pdfPTableTotalST.addCell(CELDA_ST_Total);
            pdfPTableTotalST.addCell(CELDA_ST_ps);
            pdfPTableTotalST.addCell(CELDA_ST_hogar);
            pdfPTableTotalST.addCell(CELDA_ST_Veri);
            paragraph.add(pdfPTableTotalST);
            document.add(paragraph);
        } catch (Exception e) {
            Log.e("addTitles", e.toString());
        }

    }

    private void addChild(Paragraph parrafo_interno) {
        parrafo_interno.setAlignment(Element.ALIGN_CENTER);
        paragraph.add(parrafo_interno);
    }

    public void addParagraph(String text) {
        try {
            paragraph = new Paragraph(text, fText);
            paragraph.setSpacingAfter(1);
            paragraph.setSpacingBefore(1);
            document.add(paragraph);
        } catch (Exception e) {
            Log.e("addParagraph", e.toString());
        }
    }

    public void createTable(String[] header, ArrayList<String[]> persons) {
        try {
            paragraph = new Paragraph();
            paragraph.setFont(fText);
            PdfPTable pdfPTable = new PdfPTable(header.length);
            pdfPTable.setWidthPercentage(100);
            PdfPCell pdfPCell;
            int indexC = 0;

            while (indexC < header.length) {
                pdfPCell = new PdfPCell(new Phrase(header[indexC++], fSubTitle));
                pdfPCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                pdfPCell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                pdfPTable.addCell(pdfPCell);

            }
            for (int indexR = 0; indexR < persons.size(); indexR++) {
                String[] row = persons.get(indexR);
                for (indexC = 0; indexC < header.length; indexC++) {
                    pdfPCell = new PdfPCell(new Phrase(row[indexC], fCells));
                    pdfPCell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    pdfPCell.setFixedHeight(21);
                    pdfPTable.addCell(pdfPCell);
                }

            }
            paragraph.add(pdfPTable);
            document.add(paragraph);

        } catch (Exception e) {
            Log.e("createTable", e.toString());
        }
    }

    /* public void viewPDF()         //lo quite 8 abril
     {

         Intent intent=new Intent(context,ViewPDFActivity.class);
         intent.putExtra("path",pdfFile.getAbsolutePath());
         intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
         context.startActivity(intent);
     }*/
    public void verPDF() {
        uri = FileProvider.getUriForFile(context, "com.example.proyectoproductivo", new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString() + "/PDF", "PP2020.pdf"));

        context.grantUriPermission("com.example.proyectoproductivo", uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);

//revoke permisions
        context.revokeUriPermission(uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        Intent intent = new Intent();
        intent.setAction(Intent.ACTION_SEND);
        intent.setType("application/pdf");
        intent.putExtra(Intent.EXTRA_STREAM, uri);
        List<ResolveInfo> resInfoList = context.getPackageManager().queryIntentActivities(intent, PackageManager.MATCH_DEFAULT_ONLY);
        for (ResolveInfo resolveInfo : resInfoList) {
            String packageName = resolveInfo.activityInfo.packageName;
            context.grantUriPermission(packageName, uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        }
        context.startActivity(Intent.createChooser(intent, "Enviando Archivo."));
    }
}
